### ISSUE TITLE
FileHeader: Creation date time is valid

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#13]

**Comment by wadearnold** [comment]
see #16 notes for implementing ideas.

**Comment by adamdecaf** [comment]
@wadearnold Was this (and https://github.com/moov-io/ach/issues/16) about the test cases? Aka to ensure we're validating dates?

Is there something to add in each `Validate() error` receiver method?

**Comment by adamdecaf** [comment]
This is validated in `FileCreationDateField()` and `FileCreationTimeField()`
