### ISSUE TITLE
Convert Batch to Batch with Return

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#151]
It should be possible to take an existing batch and convert it into a return batch. For example, if a batch has an entry with Insufficient funds the batch should be able to be converted into a new batch with the same values (not reference) with a AddendaReturn attached defining the R01 insufficient funds return code.

**Comment by chuckiebluestar** [comment]
The 5-record (Batch Header) of a return-6-record is identical to the original 5-record, except for Field-11 (Orig Status Code), but only if the original was received from the government; Field-12 (ODFI ID); and of course the Batch Number would be new.

**Comment by bkmoovio** [comment]
Proposal (work in progress)

Create a method Batch.CreateReturnBatchFromBatch with *Batch as the receiver.  it should return Batcher and error

Create a new returnBatchHeader from batch.GetHeader()

The default will set BatchNumber equal to 1  (batch.build should sequence correctly)

Use Case scenarios for OrginatorStautusCode
	Prepared by ACH Operator (Check with Wade if that is a use case)
		Set Batch.OrginatorStautsCode = 1
	Prepared by an Depository Financial Institution: 
		Set Batch.OrginatorStautsCode = 1
	Prepared by fedearl Agency:
		Set Batch.OrginatorStautsCode = 2

Create a returnBatch by calling function NewBatch passing returnBatchHeader

create a returnEntryDetail by ranging through batch.Entries

Create addenda99 (or any useful named variable) as NewAddenda99 
	
	Set Addenda99.OriginaltraceNumber = returnEntryDetail.TraceNumber

	Make returnCodeDict exportable?
	Set Addenda99.ReturnCode = returnCodeDict.Code
	Set Addenda99.AddendaInformation = returnCodeDict.Reason
		
			
For each returnEntryDetail set TraceNumber = "" (batch.build will set based on batch.Header.ODFIIdentificationField())

For each ReturnEntryAddenda set Addenda99 = addenda99

add returnEntryDetail to the returnBatch

After all Entries have been added to the returnBatch

Create the returnBatch (Which will call batch.build and and batch.Validate it)

Return the returnBatch

**Comment by wadearnold** [comment]
APPENDIX FOUR - Return Entries

When a Return Entry is prepared, the original Company/Batch Header Record, the original Entry
Detail Record, and the Company/Batch Control Record are copied for return to the Originator. (NOTE: This includes the original SEC code found in Field 51-53 of the Company/Batch Header Record.) 

In general, Addenda Records transmitted with the original Entry are not copied for return to the Originator. However, IAT Return Entries must include all mandatory Addenda Records Transmitted with the forward IAT Entry. (Note: IAT Addenda Records related to Foreign Correspondent Banks and those that contain remittance information are not Transmitted with IAT Return Entries.)

The Return Entry is a new Entry. These Entries must be assigned new batch and trace numbers,
new identification numbers for the returning institution, appropriate transaction codes, etc., as required per format specifications

**Comment by bkmoovio** [comment]
Wade and I walked/talked through this.  The library supports creating returns for an SEC Code, core systems using the library would create the return file (similar to creating an ACH file).
