### ISSUE TITLE
When using 200 for Service Code, output file 8 record is 92 chars instead of 94

### ISSUE THREAD

**Issue by dgolant** [moov-io/ach#157]
Hi, 

When I generate a mixed batch as follows:

```
balancedTransactionsBatch, _ := ach.NewBatch(ach.BatchParam{
			ServiceClassCode:        os.Getenv("BALANCED_SERVICE_CLASS_CODE"), // 200
			CompanyName:             os.Getenv("IMMEDIATE_DESTINATION_NAME"),
			StandardEntryClass:      os.Getenv("STANDARD_ENTRY_CLASS_CODE"), // WEB
			CompanyIdentification:   os.Getenv("IMMEDIATE_DESTINATION_ID"),
			CompanyEntryDescription: os.Getenv("COMPANY_ENTRY_DESCRIPTION"),
			ODFIIdentification:      os.Getenv("IMMEDIATE_DESTINATION_ID")})
```

I receive the error `Issue reading file: line:105 record:EntryDetail *ach.FileError RecordLength must be 94 characters and found 92`.

Line 95 is the 8 record and is the first line below:

```
800000000000000001000000000000000000000000                                   000000000000001
9000001000001000000000000000001000000000000000000000000                                       
```

Are 200 batches not supported?

**Comment by wadearnold** [comment]
The above code should generate a proper batch and 200 codes are definitely supported. It seems like one of the env variables is not getting the proper padding added to it when it is converted to a string when the file is written. If you can post an update with the os env variables that you are using it will help me find the bug.

**Comment by wadearnold** [comment]
If you can make the smallest example gist that still has the error I will get the issue resolved. It looks like one of the fields is missing two characters of padding. I just don't know which one it is OR why that would happen without an example.

**Comment by dgolant** [comment]
I've been tied up with a cold and some family obligations, apologies for the delay. 

the batch I create looks like this:
```
balancedTransactionsBatch, _ := ach.NewBatch(ach.BatchParam{
			ServiceClassCode:        "200", // always 200 for balanced
			CompanyName:             "Partner Org",
			StandardEntryClass:      "WEB",
			CompanyIdentification:   "1111111111",
			CompanyEntryDescription: "FILTRANS",
			ODFIIdentification:      "2222222222"})
```

and then I loop through a the contents of a JSON file and add transactions to the batch as detailed [here](https://gist.github.com/blackbetty/7134e6164fcd4ff636495ac25e5b1bf9)

The balanced batch is the only batch in the file, for what its worth.

**Comment by wadearnold** [comment]
This issue has been captured in #158 

Batch.Create() fixes this issue in the current release
