### ISSUE TITLE
Performance Benchmarks

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#166]
[Benchmarks](https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go) need to be added to the project so that we can gauge the effectiveness of changes as they relate to file processing. A static file created for Reading and Writing a file by running a large file (~9,999) of Entries through the library. Utilizing a mock data file performance benchmarks should be reproducible and dependable. Performance benchmarks are key to future development decisions such as validation and parallel processing of batches. 

* Add a performance benchmark test of the file utilizing [Benchmarks](https://golang.org/pkg/testing/#hdr-Benchmarks) and [Tutorial](https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go)
* Default Read performance test should mimic example use cases. Read from disk. 
* Read performance should also test file loaded into memory and then passed as a Reader to ach.Read() to negate any disk I/O discrepancies. This mimics a streaming read. 
* Write performance are separate benchmarks from the read. 
* Default Write performance test should mimic example use cases. Write to disk. 
* Write performance should also test file written into memory to mimic a streaming write (DB or API)
* Generate several large mock ach files. #165 100, 500, 2k, 5k, 10k What is the scaling performance of the library [O(n)](https://en.wikipedia.org/wiki/Big_O_notation)? 
* Add [PPROF](https://github.com/google/pprof) to generate a call graph to visualize bottlenecks. 
* Update documentation on how to run the performance benchmarks. 
* Add current performance benchmarks to the projects Readme. Include machine statistics and test file information. 
* Add benchmark test to Travis CI build file.

**Comment by adamdecaf** [comment]
For reference, NACHA states there are about ~4 million ACH files processed each day by the entire economy, so that should be our upper bound. We likely don't need to optimize further if we can process 4mil files in an hour. Maybe even as low as 100k or 1mil per hour. 

Source: https://www.nacha.org/news/nacha-reports-strong-ach-volume-growth-nearly-7-percent-q3-2018

**Comment by adamdecaf** [comment]
I was getting 13-15k/sec `Reader.Read()` calls on my mac with a bunch of stuff running.

For reference: `13000*60*60*24 = 1,123,200,000 per day`

@wadearnold Are you cool if we close this? For specific performance problems we can open a new issue.

**Comment by bkmoovio** [comment]
I think we can close this.  @wadearnold ?

**Comment by wadearnold** [comment]
I agree
