### ISSUE TITLE
Add support for IAT

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#211]
**IAT International ACH Transaction**
An IAT entry is a credit or debit ACH entry that is part of a payment transaction involving a financial agency’s office (i.e., depository financial institution or business issuing money orders) that is not located in the territorial jurisdiction of the United States. IAT entries can be made to or from a corporate or consumer account and must be accompanied by seven (7) mandatory addenda records identifying the name and physical address of the Originator, name and physical address of the Receiver, Receiver’s account number, Receiver’s bank identity and reason for the payment.

Format specification
http://docs.moov.io/en/latest/ACH_File_Structure/#iat-international-ach-transaction

**Comment by wadearnold** [comment]
Closed #228

**Comment by bkmoovio** [comment]
Thanks!

Regards,

Brooke
