### ISSUE TITLE
Add ISO 3166 validations

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#229]
Add ISO 3166-1 alpha-2 – two-letter country codes to validate country code entries (e.g. addenda13.ODFIBranchCountryCode).

Add ISO 3166-2, Codes for the representation of names of countries and their subdivisions – Part 2: Country subdivision code, defines codes for the names of the principal subdivisions (e.g., provinces, states, departments, regions) of all countries coded in ISO 3166-1, to validate subdivision entries (e.g. addenda16.ReceiverCityStateProvince)

Discussion Topic:  Is it necessary for the library, or nice to have, or not necessary.

Considerations:
  
Create proprietary validation.

Use an external vendor library (e.g. gountries, or iso3166, etc.) to validate.  This would require use of a dependency tool.

**Comment by wadearnold** [comment]
My issue with adding the dependency for ISO code validation to the library is that its only required for IAT validation. IAT in itself is an edge case of users and all users would need to now manage a dependency just for IAT. Maybe there is a way to add it as a module that would require an explicit import in the consumer's code? Something like how the standard library handles codecs for encryption and image formats in the encoders package?

**Comment by chuckiebluestar** [comment]
Are you referring to the ISO country and currency codes in IAT's? I'm
curious how different (or same) this would be from checking the validity of
RTN's when writing originated transactions?

Chuckie

**Comment by adamdecaf** [comment]
https://godoc.org/github.com/pariz/gountries looks fairly complete. We could write a layer between and ship that under `pkg/` ?

**Comment by bkmoovio** [comment]
Yes I think that would be great.  That’s great for country code validation.  I used it locally for testing.

Regards,

Brooke

**Comment by adamdecaf** [comment]
Now that https://github.com/moov-io/ach/pull/305 and https://github.com/moov-io/ach/pull/306 are merged can we close this?
