### ISSUE TITLE
Add support for IAT Returns

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#233]
IAT International ACH Transaction Returns
An IAT entry is a credit or debit ACH entry that is part of a payment transaction involving a financial agency’s office (i.e., depository financial institution or business issuing money orders) that is not located in the territorial jurisdiction of the United States. IAT entries can be made to or from a corporate or consumer account and must be accompanied by seven (7) mandatory addenda records identifying the name and physical address of the Originator, name and physical address of the Receiver, Receiver’s account number, Receiver’s bank identity and reason for the payment.  An eighth addenda record contains IAT return data. 

Format specification for IAT returns
http://docs.moov.io/en/latest/ACH_File_Structure/#iat-international-ach-transaction

**Comment by wadearnold** [comment]
Closed by #234
