### ISSUE TITLE
Change Trace Number and Original Trace Number to string

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#246]
Reference closed issues #236

A quick run of https://github.com/alecthomas/gometalinter (which can be ran for free on PR's via https://golangci.com/) gives the following error.

This would be a breaking change as int -> int64 isn't automatic.

I'm also running this on a 32-bit machine (yea, I know...), so that might be it. I thought Go defaulted int to int64 though..

$ gometalinter.v2 addenda02_test.go:23:26:error: constant 121042880000123 overflows int (vet)
addenda98_test.go:17:26:error: constant 91012980000088 overflows int (vet)
addenda98_test.go:36:29:error: constant 99912340000015 overflows int (vet)
addenda98_test.go:37:34:error: constant 99912340000015 overflows int (vet)
addenda98_test.go:45:27:error: constant 91012980000088 overflows int (vet)
addenda98_test.go:46:34:error: constant 91012980000088 overflows int (vet)
addenda99_test.go:15:28:error: constant 99912340000015 overflows int (vet)
addenda99_test.go:36:29:error: constant 99912340000015 overflows int (vet)
addenda99_test.go:37:36:error: constant 99912340000015 overflows int (vet)
addenda99_test.go:48:27:error: constant 91012980000066 overflows int (vet)
addenda99_test.go:48:27:error: too many errors (vet)
addenda02_test.go:23:26:warning: constant 121042880000123 overflows int (vetshadow)
addenda98_test.go:17:26:warning: constant 91012980000088 overflows int (vetshadow)
addenda98_test.go:36:29:warning: constant 99912340000015 overflows int (vetshadow)
addenda98_test.go:37:34:warning: constant 99912340000015 overflows int (vetshadow)
addenda98_test.go:45:27:warning: constant 91012980000088 overflows int (vetshadow)
addenda98_test.go:46:34:warning: constant 91012980000088 overflows int (vetshadow)
addenda99_test.go:15:28:warning: constant 99912340000015 overflows int (vetshadow)
addenda99_test.go:36:29:warning: constant 99912340000015 overflows int (vetshadow)
addenda99_test.go:37:36:warning: constant 99912340000015 overflows int (vetshadow)
addenda99_test.go:48:27:warning: constant 91012980000066 overflows int (vetshadow)
addenda99_test.go:48:27:warning: too many errors (vetshadow)

**Comment by adamdecaf** [comment]
@bkmoovio @wadearnold Should we do this in a `v0.5.0` release?

**Comment by wadearnold** [comment]
UGH! Can we chat about this over a hangout. Not sure how I missed this issue.

**Comment by adamdecaf** [comment]
Sure thing. I'm free today.

**Comment by adamdecaf** [comment]
FYI, this was on an old 32bit system of mine.
