### ISSUE TITLE
GET /files can leak information 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#260]
Right now the REST interface offers `GET /files`, which returns all files. This (implementation left alone) would allow anyone to scrape all generated files (say, from `api.moov.io`). We need to make this not happen.

Solutions: 
- [ ] only return files for the given auth credential (oauth, etc)
- [ ] add/document `DELETE /files/:id` and include as note on web pages 
- ~~delete files (inmem) after N minutes~~
- ~~only return files for the request IP~~

Example: 

```
 $ curl -H "Content-Type: application/json" -X GET http://localhost:8080/files/                                   

{"files":[{"id":"08B751B2","fileHeader":{"id":"08B751B2","immediateDestination":"9876543210","immediateOrigin":"1234567890","fileCreationDate":"0001-01-01T00:00:00Z","file\CreationTime":"0001-01-01T00:00:00Z","fileIDModifier":"A","immediateDestinationName":"Federal Reserve Bank","immediateOriginName":"My Bank Name"},"batches":null,"IATBatche\s":null,"fileControl":{"id":"08B751B2","batchCount":0,"entryAddendaCount":0,"entryHash":0,"totalDebit":0,"totalCredit":0},"NotificationOfChange":null,"ReturnEntries":null}\]}
```

**Comment by wadearnold** [comment]
I am ok with the REST endpoint not being multi-tenant in its initial release. Many users will use this library locally or behind a service to generate a file. Maybe we need to assign this to a new milestone for exposing the endpoint to the internet?

**Comment by adamdecaf** [comment]
https://github.com/moov-io/infra/commit/721bf809a4630b8d60ef83c8d2598f89a3295246 requires cookie auth around the endpoint now, but the endpoint doesn't check for a userId.

**Comment by adamdecaf** [comment]
Our LB (traefik) will [forward request headers over to `auth` which verifies the cookie](https://github.com/moov-io/infra/blob/b555a819ce5f44ab09ed30f8a4b2b50894d91fa6/lib/apps/10-ach.yaml#L30-L32). On a successful cookie/oauth check `auth` responds with `X-User-Id` whose value is our userId string for this user. A non-empty string here can be assumed to mean successful auth. 

`ach` could then [extract the userId](https://github.com/moov-io/paygate/blob/94323f98cfdb027b9b08efd2b03221f02639bd47/http.go#L41-L45) and use it in response logic. (i.e. serve ACH files by userId)
