### ISSUE TITLE
ACH File naming convention

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#301]
ACH File names should follow the following convention:

A good file-naming convention would be NNNyyyyMMdd-RTNRTNRTN-X.ach

Where:  
NNN  = An acronym or abbreviation for the company (originator or receiver) `MOO`
yyyy =  Year of file creation `2018`
MM  =  Month of file creation `12`
dd   =   Day of file creation `22`
RTN . . . = 9-digit Routing Transit Number of the bank (ODFI or RDFI) `301234567`
X = file sequence of the day, i.e., A, B, C, D  `A`

`MOO20181222-301234567-A.ach`

**Comment by adamdecaf** [comment]
We only write files in `cmd/writeACH`, are we talking about just that?

If we're adding support to `Writer` then I propose adding: 
```Go
type Writer struct {
        Format string // defaults to YYMMDD.ach
}

// func (w *Writer) ToFile() (*os.File, error) 

// If dir is empty use os.Getcwd() 
// func (w *Writer) ToFile(dir string) (*os.File, error)  
```

**Comment by bkmoovio** [comment]
I have no idea you guys asked me to create an issue.  I thought I was clear in that in my slack communication.  I presumed the api.  I don’t mind being an admin for you and writing issues up but just tell me what it is for.

Regards,

Brooke

**Comment by wadearnold** [comment]
all good. Ill write it up.

**Comment by wadearnold** [comment]
Because of the writer being an io.Writer it doesn't make sense to add this as an output. I could see it as a property of the File.ach

**Comment by adamdecaf** [comment]
> I could see it as a property of the File.ach

I'm not sure what you mean by this.

I am in favor of changing `cmd/writeACH` to output file names according to the proposed format above.

**Comment by bkmoovio** [comment]
Wouldn't whoever is using the library define it?  I believe that format is what some banks legacy core systems use.

**Comment by wadearnold** [comment]
This issue should be moved to the PayGate repository

**Comment by adamdecaf** [comment]
This was done as part of https://github.com/moov-io/paygate/pull/96
