### ISSUE TITLE
Test: ach-web-read|write

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#307]
**What were you trying to do?**

Find an example for reading and writing a WEB transaction in the source code. Currently one is in the README.md

**What did you expect to see?**

A folder in the /test/ach-web-read/ and test/ach-web-write/ directory that implements the WEB SEC code

**What did you see?**

Examples of other SEC codes but not web.

**Comment by bkmoovio** [comment]
I'll pick this up.
