### ISSUE TITLE
Replace panic(err) and log(err) and use t.fatal in _test.go files

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#332]
**What were you trying to do?**

Run tests without panic(err) or log(err)

**What did you expect to see?**

All failed test return errors.

**What did you see?**

If more than one test failed and panic(err) was returned, the test stoppped

**How can we reproduce the problem?**

Modify a mockBatch*  to return an error on create

```
// mockBatchCCD creates a CCD batch
func mockBatchCCD() *BatchCCD {
	mockBatch := NewBatchCCD(mockBatchCCDHeader())
	mockBatch.AddEntry(mockCCDEntryDetail())
	mockBatch.GetEntries()[0].AddAddenda(mockAddenda02())
	if err := mockBatch.Create(); err != nil {
		panic(err)
	}
	return mockBatch
}
```

```
// mockBatchACK creates a ACK batch
func mockBatchACK() *BatchACK {
	mockBatch := NewBatchACK(mockBatchACKHeader())
	mockBatch.AddEntry(mockACKEntryDetail())
	mockBatch.GetEntries()[0].AddAddenda(mockAddenda02())
	if err := mockBatch.Create(); err != nil {
		log.Fatal(err)
	}
	return mockBatch
} 
```

**Comment by adamdecaf** [comment]
Thinking about this again it's more of a "meh, cleanup" issue. IMO this should be those helper methods taking `t *testing.T` and calling `t.Helper()`. That's the proper way to do this, but then a `t` is always needed. 

Marking as chore incase someone wants to do this.

**Comment by adamdecaf** [comment]
This was done.

**Comment by adamdecaf** [comment]
Brooke and I decided against doing this.
