### ISSUE TITLE
replace EntryDetail.Addendum with specific fields for each AddendaXX record

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#341]
`EntryDetail.Addendum` (and `Addendumer`) are confusing. Certain SEC codes have limits on which addendas (and how many) are allowed for each batch. 

This is a proposal to remove `Addendumer` and replace `EntryDetail.Addendum` with:

For IAT Addenda10-Addenda16 should not be addendumer.  Addenda17-Addenda18 should be changed from addendumer. 

```Go
    Addenda02 *Addenda02 `json:"addenda02,omitempty"`
    Addenda05 []*Addenda05 `json:"addenda05,omitempty"`
    Addenda98 *Addenda98 `json:"addenda98,omitempty"`
    Addenda99 *Addenda98 `json:"addenda99,omitempty"`
```

Note: The AddendaXX fields should mention what SEC codes they're valid for, so they show up in the godoc.

**Comment by bkmoovio** [comment]
The following ToDo in iatBatch will be removed:

	// Addendum a list of Addenda for the Entry Detail.  For IAT the addendumer is currently being used
	// for the optional Addenda17 and Addenda18 records.
	// ToDo: Consider reverting Addenda* explicit properties back to being addendumer

**Comment by adamdecaf** [comment]
https://github.com/moov-io/ach/pull/352 was the fix
