### ISSUE TITLE
Support DNE  - Death Notification Entry

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#342]
DNE - Death Notification Entry - This application is utilized by a federal government agency (e.g., Social Security Administration) to notify a depository financial institution that the recipient of a government benefit payment has died.

- [x] Library should support the reading and writing of DNE records.
- [x] Document the DNE record format on the documentation website. 
- [x] Create a test example for the reading and writing of DNE records

**Comment by bkmoovio** [comment]
Nice!

**Comment by adamdecaf** [comment]
I mis-read part of the spec. The PaymentRelatedInformation is formatted differently.
