### ISSUE TITLE
proposal:  cmd/ach: command line tool

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#356]
moovach  
========

Converts a stream of ACH input data (TXT, JSON, CSV) to a designated output format. 

[![Build Status](https://travis-ci.com/moov-io/ach.png?branch=master)](https://travis-ci.com/moov-io/ach)

Installation
============

pre-built binaries are available under [releases](https://github.com/moov-io/ach/releases).

If you have a working golang install, you can use `go get`.

```bash
go get github.com/moov-io/ach/cmd/ach
```

Usage
=====

```
usage: moovach
    -i /path/to/input.json (optional; default is stdin)
    -o /path/to/output.csv (optional; default is stdout)
    // -b build a valid ach file from the input stream // TODO: see comments below
    -f [TXT,JSON,CSV] defines format of input and output
    --version
    -h This help
```

To convert:

```json
{"files":[{"id":"fmucllmgqkaxcjowdoko","fileHeader":{"id":"fmucllmgqkaxcjowdoko","immediateDestination":"231380104","immediateOrigin":"121042882","fileCreationDate":"2018-10-08T00:00:00Z","fileCreationTime":"2018-10-08T00:00:00Z","fileIDModifier":"A","immediateDestinationName":"Federal Reserve Bank","immediateOriginName":"My Bank Name"},"batches":[{"batchHeader":{"id":"fmucllmgqkaxcjowdoko","serviceClassCode":200,"companyName":"Your Company, Inc","companyIdentification":"121042882","standardEntryClassCode":"PPD","companyEntryDescription":"Online Order","effectiveEntryDate":"2018-10-09T00:00:00Z","ODFIIdentification":"12104288","batchNumber":1},"entryDetails":[{"id":"fmucllmgqkaxcjowdoko","transactionCode":22,"RDFIIdentification":"23138010","checkDigit":"4","DFIAccountNumber":"81967038518      ","amount":100000,"identificationNumber":"#83738AB#      ","individualName":"Steven Tander         ","discretionaryData":"  ","addendaRecordIndicator":1,"traceNumber":121042880000001,"category":"Forward"}],"batchControl":{"id":"fmucllmgqkaxcjowdoko","serviceClassCode":200,"entryAddendaÇount":0,"entryHash":0,"totalDebit":0,"totalCredit":0,"companyIdentification":"121042882","ODFIIdentification":"12104288","batchNumber":1}}],"IATBatches":null,"fileControl":{"id":"","batchCount":1,"blockCount":1,"entryAddendaCount":0,"entryHash":0,"totalDebit":0,"totalCredit":0},"NotificationOfChange":null,"ReturnEntries":null}],"error":null}

```

to:

```
101 231380104 1210428821810080000A094101Federal Reserve Bank   My Bank Name                   
200Your Company, In                    121042882 PPDOnline Ord      181009   0121042880000001
2223138010481967038518      0000100000#83738AB#      Steven Tander           1121042880000001
2000000000000000000000000000000000000000000121042882                          121042880000001
9000001000001000000000000000000000000000000000000000000                                       
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
```
    
you would either

```bash
ach  -i achfile.json -o achfile.txt
```

or

```bash
cat achfile.json | ach -f TXT > achfile.txt
```

**Comment by adamdecaf** [comment]
Would this replace `cmd/readACH` and `cmd/writeACH` (merge those together)? 

> `go get github.com/moov-io/ach/cmd`

We already have `cmd/server`, so this would be `go get github.com/moov-io/ach/cmd/moovach`.

**Comment by adamdecaf** [comment]
> -b build a valid ach file from the input stream 

I don't think this flag is needed. Isn't this the default action?

**Comment by wadearnold** [comment]
> I don't think this flag is needed. Isn't this the default action?

You are right that should be the default. We should really override it the other way. If they don't want it built.

**Comment by wadearnold** [comment]
> We already have `cmd/server`, so this would be `go get github.com/moov-io/ach/cmd/moovach`.

I think that these get moved to the following. 

```
› ach
.
└── cmd
    ├── ach
    │   └── main.go
    └── server
        └── main.go
```
If we moved the programs to their own subfolders in our workspace, when built (and installed) they will inherit the name of the folder they are in. Therefore, cmd/server/main.go will compile into a server binary, while cmd/ach/main.go will compile into a ach binary. Then, after buildilng, these binaries will be installed into the Go binaries path ($GOPATH/bin).

**Comment by wadearnold** [comment]
> Would this replace `cmd/readACH` and `cmd/writeACH` (merge those together)?

These two files were created to generate test data to be used in benchmarking. I am not sure where they need to end up now or if they have already served there purpose.

**Comment by adamdecaf** [comment]
We could keep `cmd/writeACH` around for fuzz corpus generation, but `readACH` might be better suited as a `-dump` / `-show` option on `moovach`.

**Comment by adamdecaf** [comment]
I updated the title and original description to match changes we talked about.

**Comment by adamdecaf** [comment]
`achcli` has been working well for this case https://github.com/moov-io/ach#command-line
