### ISSUE TITLE
proposal: cmd/ach: -cost flag 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#359]
Following from https://github.com/moov-io/ach/issues/356 (`ach` command line tool proposal) the NACHA rules specify a cost breakdown:

- Per-Entry Fee (Jan 1 - Dec 31): `$0.000145`
- Annual Fee: `$144.00`

We could _estimate_ the cost per-file (or for a group of files) and return. At a later point we could factor this into file consolidation logic. 

```
$ ach -cost -i customer1.ach -i customer2.ach
customer1.ach: $0.02 
customer2.ach: $0.000145
Total: $0.020145
```

```
$ ach -cost -i customer*
customer1.ach: $0.02 
customer2.ach: $0.000145
Total: $0.020145
```

Please upvote if you'd find this useful.

**Comment by vxio** [comment]
This issue was create a while back, @adamdecaf do you think this feature would still be useful?

**Comment by adamdecaf** [comment]
Probably not as a CLI flag. We can revisit it later.
