### ISSUE TITLE
docs: Improve hello world velocity for beginners

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#380]
**What were you trying to do?**

As a developer without ACH experience I need to integrate Moov's software into my business needs. The faster I'm able to iterate, develop code and ship the happier I am. Ideally the software is consistent and intuitive.

**Comment by adamdecaf** [comment]
Looking at the following popular projects README's: [hugo](https://github.com/gohugoio/hugo) | [caddy](https://github.com/mholt/caddy) | [etcd](https://github.com/etcd-io/etcd) | [terraform](https://github.com/hashicorp/terraform) | [mattermost](https://github.com/mattermost/mattermost-server) (FOSS chat app).

Roughy, the order of each README follows: 

1. Logo
2. Links to community, documentation, build status, etc
3. Short, concise, and compelling feature list
   - Some contain examples
4. Install / Download / Build
5. Contributing
   - Issues, Code / PR, testing, feature requests

**Comment by adamdecaf** [comment]
@wadearnold Do you have suggestions for further improvements? https://github.com/moov-io/ach/pull/379 improves the README quite a lot. We'll expand as people give us feedback, but I'm not sure how much more detail to include.

**Comment by bkmoovio** [comment]
What still needs to be done on this?

**Comment by adamdecaf** [comment]
I'm not really sure. It'd be nice to have some newbies take a look and tell us what's confusing or missing.

**Comment by bkmoovio** [comment]
Users have created and sent test cases prior to these updates.  Should we close?
