### ISSUE TITLE
addendaFieldInclusion* discussion

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#396]
Discussion topic: function: batch.addendaFieldInclusion:

Do we want to refactor this logic into the specific BatchType(s)? Currently this is generic function called from each BatchType -

Taken from the view point of developer/designer/IT lead/ IT Manage/Tester in which there have been both functional and technical specifications for the original code and enhancements I have experienced similar cases where it becomes challenging to maintain and enhance this type of code over time as the conditionals can become confusing (gocyclo complex) to understand and there can be crossovers between the conditionals.  Even with well written test cases, there are misses. 

The worst case scenario issue is needing a change for one SEC Code (example ARC), the change is done, tested, approved, pushed into production, and PPD and WEB breaks because of it.  Effectively shutting the business down or costing the business  $$$$.  The question asked from top down is we only needed a change to ARC, why did it break PPD and WEB.  

There are all kinds of answers, processes, and tests that can be put in place to solve for this but it still happens.  This sometimes leads to the worst case solution, which is the system doesn't 'really' get enhanced, because of the risk; or the system isn't actually used as intended and custom code that (using this topic) is BatchType specific is written by each institution using the system.   

The con to having it be in each BatchType is if changes are needed for all the BatchTypes, it is tedious work, although the IDE's today make that a bit easier to handle with some of the features of the IDE such as refactor functionality and find in files/path, etc, and having the ability to drill directly into the code. 
 
If we keep the function would we  we want to make this function exportable so a client can access it?

Other open discussion points on this topic...

**Comment by bkmoovio** [comment]
```Go
func (batch *Batch) addendaFieldInclusion(entry *EntryDetail) error {
	switch entry.Category {
	case CategoryForward:
		if err := batch.addendaFieldInclusionForward(entry); err != nil {
			return err
		}
	case CategoryNOC:
		if err := batch.addendaFieldInclusionNOC(entry); err != nil {
			return err
		}
	case CategoryReturn, CategoryDishonoredReturn, CategoryDishonoredReturnContested:
		if err := batch.addendaFieldInclusionReturn(entry); err != nil {
			return err
		}
	}
	return nil
}

// addendaFieldInclusionForward verifies Addenda* Field Inclusion for entry.Category Forward
func (batch *Batch) addendaFieldInclusionForward(entry *EntryDetail) error {
	switch batch.Header.StandardEntryClassCode {
	case MTE, POS, SHR:
		if entry.Addenda02 == nil {
			return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda02", Msg: msgFieldInclusion}

		}
		if entry.Addenda05 != nil {
			msg := fmt.Sprintf(msgBatchAddenda, "Addenda05", entry.Category, batch.Header.StandardEntryClassCode)
			return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda05", Msg: msg}
		}
	// ACK, ATX, CCD, CIE, CTX, DNE, ENR WEB, PPD, TRX can only have Addenda05
	case ACK, ATX, CCD, CIE, CTX, DNE, ENR, WEB, PPD, TRX:
		if entry.Addenda02 != nil {
			msg := fmt.Sprintf(msgBatchAddenda, "Addenda02", entry.Category, batch.Header.StandardEntryClassCode)
			return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda02", Msg: msg}
		}
	case ARC, BOC, COR, POP, RCK, TEL, TRC, XCK:
		if entry.Addenda02 != nil {
			msg := fmt.Sprintf(msgBatchAddenda, "Addenda02", entry.Category, batch.Header.StandardEntryClassCode)
			return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda02", Msg: msg}
		}
		if entry.Addenda05 != nil {
			msg := fmt.Sprintf(msgBatchAddenda, "Addenda05", entry.Category, batch.Header.StandardEntryClassCode)
			return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda05", Msg: msg}
		}
	}
	if batch.Header.StandardEntryClassCode != COR {
		if entry.Addenda98 != nil {
			msg := fmt.Sprintf(msgBatchAddenda, "Addenda98", entry.Category, batch.Header.StandardEntryClassCode)
			return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda98", Msg: msg}
		}
	}
	if entry.Addenda99 != nil {
		msg := fmt.Sprintf(msgBatchAddenda, "Addenda99", entry.Category, batch.Header.StandardEntryClassCode)
		return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda99", Msg: msg}
	}
	return nil
}

// addendaFieldInclusionNOC verifies Addenda* Field Inclusion for entry.Category NOC
func (batch *Batch) addendaFieldInclusionNOC(entry *EntryDetail) error {
	if entry.Addenda02 != nil {
		msg := fmt.Sprintf(msgBatchAddenda, "Addenda02", entry.Category, batch.Header.StandardEntryClassCode)
		return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda02", Msg: msg}
	}
	if entry.Addenda05 != nil {
		msg := fmt.Sprintf(msgBatchAddenda, "Addenda05", entry.Category, batch.Header.StandardEntryClassCode)
		return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda05", Msg: msg}
	}
	if batch.Header.StandardEntryClassCode != COR {
		if entry.Addenda98 != nil {
			return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda98", Msg: msgFieldInclusion}
		}
	}
	if entry.Addenda99 != nil {
		msg := fmt.Sprintf(msgBatchAddenda, "Addenda99", entry.Category, batch.Header.StandardEntryClassCode)
		return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda99", Msg: msg}
	}
	return nil
}

// addendaFieldInclusionReturn verifies Addenda* Field Inclusion for entry.Category Return
func (batch *Batch) addendaFieldInclusionReturn(entry *EntryDetail) error {
	if entry.Addenda02 != nil {
		msg := fmt.Sprintf(msgBatchAddenda, "Addenda02", entry.Category, batch.Header.StandardEntryClassCode)
		return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda02", Msg: msg}
	}
	if entry.Addenda05 != nil {
		msg := fmt.Sprintf(msgBatchAddenda, "Addenda05", entry.Category, batch.Header.StandardEntryClassCode)
		return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda05", Msg: msg}
	}
	if entry.Addenda98 != nil {
		msg := fmt.Sprintf(msgBatchAddenda, "Addenda98", entry.Category, batch.Header.StandardEntryClassCode)
		return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda98", Msg: msg}
	}
	if entry.Addenda99 == nil {
		return &BatchError{BatchNumber: batch.Header.BatchNumber, FieldName: "Addenda99", Msg: msgFieldInclusion}
	}
	return nil
}
```

**Comment by adamdecaf** [comment]
> The worst case scenario issue is needing a change for one SEC Code (example ARC), the change is done, tested, approved, pushed into production, and PPD and WEB breaks because of it.

How often would this happen? My assumption would be a developer using our `ach` library creates multiple paths in their code for different batch types (or uses paygate instead). Do projects change SEC codes that often?

**Comment by bkmoovio** [comment]
Since the library has support for all SEC codes, It shouldn't occur unless there is a change to the entryDetail (Batchheader, BatchControl, etc. ...)  requirements  for an SEC Code (which probably isn't often) or there is a defect.  If there is a defect that needs to be fixed, the library has some Batch Type isolation built in, which is great.

With regards to any deployed code (not specific to ACH)  in a production environment a production support issue that arises can present the issue of testing isolated changes that are intertwined generically which may impact other parts of the system. 

From the library perspective we your assumption is correct (a developer using our ach library creates multiple paths in their code for different batch types or uses paygate instead )

**Comment by bkmoovio** [comment]
No change will be made
