### ISSUE TITLE
Documentation: Curl / Postman examples for building files 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#399]
Moov ACH exposes a RESTful endpoint to create ach files. We should supply a curl or postman based example of interacting with the API for file creation.

**Comment by bkmoovio** [comment]
```json
{
	"fileHeader": {
		"immediateOrigin": "121042882",
		"immediateOriginName": "Origin Bank",
		"immediateDestination": "231380104",
		"immediateDestinationName": "Destination Bank",
		"fileCreationDate": "2018-12-12T00:00:00Z",
		"fileCreationTime": "2018-12-12T11:39:05Z",
		"fileIDModifier": "A"
	},
	"id": "",
	"batches": [
		{
		"batchHeader": {
			"serviceClassCode": 220,
			"companyIdentification": "121042882", 
			"companyName": "Company Name",
			"ODFIIdentification": "121042882",
			"id": "",
			"companyDiscretionaryData": "",
			"standardEntryClassCode": "PPD",
			"companyEntryDescription": "PAYROLL",
			"companyDescriptiveDate": "122018",
			"effectiveEntryDate": "2018-12-12T00:00:00Z",
			"originatorStatusCode": 1,
			"batchNumber": 1
		},
		"entryDetails": [
			{
			"id": "",
			"transactionCode": 22,
			"RDFIIdentification": "23138010",
			"checkDigit": "4",
			"DFIAccountNumber": "123456789",
			"amount": 200000,
			"individualName": "Edward James",
			"identificationNumber": "26",
			"discretionaryData": "",
			"addendaRecordIndicator": 0,
			"traceNumber": "",
			"addenda02": null,
			"addenda05": [
				{
				"paymentRelatedInformation": "December Payroll",
				"sequenceNumber": 1,
				"entryDetailSequenceNumber": 1
				
				}
			],
			"addenda98": null,
			"addenda99": null,
			"category": "Forward"
			}
		]
	}
	]
}
```

**Comment by adamdecaf** [comment]
I don't think we should include a curl example. If people really want they can use our moov.io/demo and "Copy as cURL" from Chrome's dev tools.

**Comment by wadearnold** [comment]
Sounds good

**Comment by bkmoovio** [comment]
Adam created a valid ppd json file as well.  I will continue working on POSTMAN collection as well.

**Comment by adamdecaf** [comment]
If needed we could always reference https://github.com/moov-io/ach/blob/master/test/testdata/ppd-valid.json as a JSON payload. It's used in tests so it'll always be valid. 

https://raw.githubusercontent.com/moov-io/ach/master/test/testdata/ppd-valid.json

**Comment by bkmoovio** [comment]
Yes, that is what I was referring too.  RE: 'Adam created a valid ppd json file as well'.   I think this issue can be closed.  @wadearnold and @adamdecaf do you agree?

**Comment by bkmoovio** [comment]
That is pretty cool Adam: using  "Copy as cURL" from Chrome's dev tools.

I was able to generate this from generate code snippets cURL in postman.  Pretty cool.

curl -X POST \
  https://api.moov.io/v1/ach/files/create \
  -H 'Content-Type: application/json' \
  -H 'Cookie: ' \
  -H 'Postman-Token: 70318d8d-e5c9-4870-bd45-bd143c06fc01' \
  -H 'X-Idempotency-Key: "<string>"' \
  -H 'X-Request-Id: "<string>"' \
  -H 'cache-control: no-cache' \
  -d '{
	"fileHeader": {
		"immediateOrigin": "121042882",
		"immediateOriginName": "Origin Bank",
		"immediateDestination": "231380104",
		"immediateDestinationName": "Destination Bank",
		"fileCreationDate": "2018-12-12T00:00:00Z",
		"fileCreationTime": "2018-12-12T11:39:05Z",
		"fileIDModifier": "A",
		"id": "bkp487"
	},
	"id": "bkp487",
	"batches": [
		{
		"batchHeader": {
			"serviceClassCode": 220,
			"companyIdentification": "121042882", 
			"companyName": "Company Name",
			"ODFIIdentification": "121042882",
			"id": "",
			"companyDiscretionaryData": "",
			"standardEntryClassCode": "PPD",
			"companyEntryDescription": "PAYROLL",
			"companyDescriptiveDate": "122018",
			"effectiveEntryDate": "2018-12-12T00:00:00Z",
			"originatorStatusCode": 1,
			"batchNumber": 1
		},
		"entryDetails": [
			{
			"id": "bkp487",
			"transactionCode": 22,
			"RDFIIdentification": "23138010",
			"checkDigit": "4",
			"DFIAccountNumber": "123456789",
			"amount": 200000,
			"individualName": "Edward James",
			"identificationNumber": "26",
			"discretionaryData": "",
			"addendaRecordIndicator": 0,
			"traceNumber": "",
			"addenda02": null,
			"addenda05": [
				{
				"paymentRelatedInformation": "December Payroll"		
				}
			],
			"addenda98": null,
			"addenda99": null,
			"category": "Forward"
			}
		]
	}
	]
}'

**Comment by adamdecaf** [comment]
@bkmoovio does Postman fill in fields correctly from the OpenAPI spec file? Yesterday you were running into problems with `"addenda02": ""` which isn't valid (should be `null` or an object `{ ... }`).

If Postman can't generate the JSON properly we shouldn't offer it as an option and file a bug upstream.

**Comment by bkmoovio** [comment]
I think it will be fine, once updated

Yesterday for the collection I created by import from link: https://raw.githubusercontent.com/moov-io/api/master/openapi.yaml,  some POST requests had schema included in the body, others did not.  I have not delved into why yet.   Addendum was included (and still is today) with Create a new File Object POST request, so it is not up to date.  I would like to see what the schema looks like for Addenda02, Addenda05, etc.

{
    "fileHeader": {
        "immediateOrigin": "<string>",
        "immediateOriginName": "<string>",
        "immediateDestination": "<string>",
        "immediateDestinationName": "<string>",
        "fileCreationDate": "<string>",
        "fileCreationTime": "<string>",
        "fileIDModifier": "<string>"
    },
    "id": "<string>",
    "batches": [
        {
            "batchHeader": {
                "serviceClassCode": "<integer>",
                "companyName": "<string>",
                "ODFIIdentification": "<string>",
                "id": "<string>",
                "companyDiscretionaryData": "<string>",
                "standardEntryClassCode": "<string>",
                "companyEntryDescription": "<string>",
                "companyDescriptiveDate": "<string>",
                "effectiveEntryDate": "<dateTime>",
                "originatorStatusCode": "<integer>",
                "batchNumber": "<string>"
            },
            "entryDetails": [
                {
                    "id": "<string>",
                    "transactionCode": "<integer>",
                    "RDFIIdentification": "<string>",
                    "checkDigit": "<string>",
                    "DFIAccountNumber": "<string>",
                    "amount": "<integer>",
                    "individualName": "<string>",
                    "identificationNumber": "<string>",
                    "discretionaryData": "<string>",
                    "addendaRecordIndicator": "<integer>",
                    "traceNumber": "<integer>",
                    "addendum": [
                        {
                            "typeCode": "<string>"
                        },
                        {
                            "typeCode": "<string>"
                        }
                    ],
                    "category": "<string>"
                },
                {
                    "id": "<string>",
                    "transactionCode": "<integer>",
                    "RDFIIdentification": "<string>",
                    "checkDigit": "<string>",
                    "DFIAccountNumber": "<string>",
                    "amount": "<integer>",
                    "individualName": "<string>",
                    "identificationNumber": "<string>",
                    "discretionaryData": "<string>",
                    "addendaRecordIndicator": "<integer>",
                    "traceNumber": "<integer>",
                    "addendum": [
                        {
                            "typeCode": "<string>"
                        },
                        {
                            "typeCode": "<string>"
                        }
                    ],
                    "category": "<string>"
                }
            ],
            "batchControl": {
                "id": "<string>",
                "serviceClassCode": "<integer>",
                "entryAddendaÇount": "<integer>",
                "entryHash": "<integer>",
                "totalDebit": "<integer>",
                "totalCredit": "<integer>",
                "companyIdentification": "<string>",
                "messageAuthentication": "<string>",
                "ODFIIdentification": "<string>",
                "batchNumber": "<string>"
            }
        },
        {
            "batchHeader": {
                "serviceClassCode": "<integer>",
                "companyName": "<string>",
                "ODFIIdentification": "<string>",
                "id": "<string>",
                "companyDiscretionaryData": "<string>",
                "standardEntryClassCode": "<string>",
                "companyEntryDescription": "<string>",
                "companyDescriptiveDate": "<string>",
                "effectiveEntryDate": "<dateTime>",
                "originatorStatusCode": "<integer>",
                "batchNumber": "<string>"
            },
            "entryDetails": [
                {
                    "id": "<string>",
                    "transactionCode": "<integer>",
                    "RDFIIdentification": "<string>",
                    "checkDigit": "<string>",
                    "DFIAccountNumber": "<string>",
                    "amount": "<integer>",
                    "individualName": "<string>",
                    "identificationNumber": "<string>",
                    "discretionaryData": "<string>",
                    "addendaRecordIndicator": "<integer>",
                    "traceNumber": "<integer>",
                    "addendum": [
                        {
                            "typeCode": "<string>"
                        },
                        {
                            "typeCode": "<string>"
                        }
                    ],
                    "category": "<string>"
                },
                {
                    "id": "<string>",
                    "transactionCode": "<integer>",
                    "RDFIIdentification": "<string>",
                    "checkDigit": "<string>",
                    "DFIAccountNumber": "<string>",
                    "amount": "<integer>",
                    "individualName": "<string>",
                    "identificationNumber": "<string>",
                    "discretionaryData": "<string>",
                    "addendaRecordIndicator": "<integer>",
                    "traceNumber": "<integer>",
                    "addendum": [
                        {
                            "typeCode": "<string>"
                        },
                        {
                            "typeCode": "<string>"
                        }
                    ],
                    "category": "<string>"
                }
            ],
            "batchControl": {
                "id": "<string>",
                "serviceClassCode": "<integer>",
                "entryAddendaÇount": "<integer>",
                "entryHash": "<integer>",
                "totalDebit": "<integer>",
                "totalCredit": "<integer>",
                "companyIdentification": "<string>",
                "messageAuthentication": "<string>",
                "ODFIIdentification": "<string>",
                "batchNumber": "<string>"
            }
        }
    ],
    "IATBatches": [
        {
            "id": "<string>",
            "IATBatchHeader": {
                "id": "<string>",
                "serviceClassCode": "<integer>",
                "IATIndicator": "<string>",
                "foreignExchangeIndicator": "<string>",
                "foreignExchangeReferenceIndicator": "<integer>",
                "foreignExchangeReference": "<string>",
                "ISODestinationCountryCode": "<string>",
                "originatorIdentification": "<string>",
                "standardEntryClassCode": "<string>",
                "companyEntryDescription": "<string>",
                "ISOOriginatingCurrencyCode": "<string>",
                "ISODestinationCurrencyCode": "<string>",
                "effectiveEntryDate": "<string>",
                "originatorStatusCode": "<integer>",
                "ODFIIdentification": "<string>",
                "batchNumber": "<integer>"
            }
        },
        {
            "id": "<string>",
            "IATBatchHeader": {
                "id": "<string>",
                "serviceClassCode": "<integer>",
                "IATIndicator": "<string>",
                "foreignExchangeIndicator": "<string>",
                "foreignExchangeReferenceIndicator": "<integer>",
                "foreignExchangeReference": "<string>",
                "ISODestinationCountryCode": "<string>",
                "originatorIdentification": "<string>",
                "standardEntryClassCode": "<string>",
                "companyEntryDescription": "<string>",
                "ISOOriginatingCurrencyCode": "<string>",
                "ISODestinationCurrencyCode": "<string>",
                "effectiveEntryDate": "<string>",
                "originatorStatusCode": "<integer>",
                "ODFIIdentification": "<string>",
                "batchNumber": "<integer>"
            }
        }
    ],
    "fileControl": {
        "id": "<string>",
        "batchCount": "<integer>",
        "blockCount": "<integer>",
        "entryAddendaCount": "<integer>",
        "entryHash": "<integer>",
        "totalDebit": "<integer>",
        "totalCredit": "<integer>"
    }
}

Today POST for create a Customer, Originator, and Depository have schema within the body

e.g,

{
    "bankName": "<string>",
    "holder": "<string>",
    "holderType": "<string>",
    "type": "<string>",
    "routingNumber": "<string>",
    "accountNumber": "<string>",
    "parent": "<string>",
    "metadata": "<string>"
}

**Comment by bkmoovio** [comment]
I presume it will be:

addenda02 {...}
addenda05 [{...}] , etc.

**Comment by bkmoovio** [comment]
The schema also had fileControl, batchControl, IAT* so I had to manipulate it some.  I still think we want better error messaging.  Does unmarshal JSON to a golang struct know what property failed?

**Comment by adamdecaf** [comment]
> Does unmarshal JSON to a golang struct know what property failed?

Yes - https://play.golang.org/p/Gs_ABNezbAd 

```
json: cannot unmarshal number into Go struct field obj.other of type string
```

**Comment by bkmoovio** [comment]
so... it would be great if go returned a more user/developer friendly message.    HA!

**Comment by bkmoovio** [comment]
first constants, then developer friendly error message.  Forget about it...
