### ISSUE TITLE
Megacheck has been deprecated. Please use staticcheck instead.

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#430]
**What were you trying to do?**

Creating a test for:  https://github.com/moov-io/ach/issues/429

Added a new same day ach test to moov-io/ach/test, and pushed to github

**What did you expect to see?**

megacheck return without error

**What did you see?**

Megacheck has been deprecated. Please use staticcheck instead.
file.go:308:9: assigning the result of this type assertion to a variable (switch batch := batch.(type)) could eliminate the following type assertions:
/home/travis/gopath/src/github.com/moov-io/ach/file.go:310:59 (S1034)
server/repository.go:34:34: should use make(map[string]*ach.File) instead (S1019)
The command "megacheck ./..." exited with 1.

**How can we reproduce the problem?**

push a moov-io/ach change and let the build run.

**Comment by bkmoovio** [comment]
Draft Proposal:

**Breaking Change**

Instead of using make(map[string])*ach.File) -- as suggested from staticcheck

Change file.NotificationOfChange from type *[]BatchCOR to type  []Batcher

Modify  file.AddBatch Check batch.Category == CategoryNOC instead of the type assertion.

Add mockPPDEntryDetailNOC which creates a PPD NOC Entry Detail (specifically setting entry.Category = CategoryNOC

Modify file_test.testFileNotificationOfChange to use mockPPDEntryDetailNOC

Update .travis.yml
Remove:
   - go get -u honnef.co/go/tools/cmd/megacheck
   megacheck ./...
Add:
- go get -u honnef.co/go/tools/staticcheck
  staticcheck ./...

**Comment by adamdecaf** [comment]
FYI, the daily cron to rebuild/test must have broken in the travis-ci org -> com move. I had those setup to catch these trivial errors that break the build. I fix.
