### ISSUE TITLE
COR Transaction Code 21 validation error

### ISSUE THREAD

**Issue by adelelopez** [moov-io/ach#457]
Test `testBatchCORTransactionCode21`: https://github.com/adelelopez/ach/blob/master/batchCOR_test.go#L275 is not returning any errors, but the code looks like it is checking for an error. The very similar test `testBatchCORTransactionCode27` here https://github.com/adelelopez/ach/blob/master/batchCOR_test.go#L246 returns the expected error, for example. 

If this is working as expected, we should add a comment to that effect.

**Comment by bkmoovio** [comment]
I figured anybody that was looking at the tests would know a 21 shouldn't get the error and a 27 should. Bad presumption on my part so I can add comments.   But please right up an issue and include the tests that are failing so I can address them.  One issue with the all of tests that are failing should be fine.

**Comment by adelelopez** [comment]
This was the only test with this kind of issue.
