### ISSUE TITLE
Addenda count and category validation issues

### ISSUE THREAD

**Issue by adelelopez** [moov-io/ach#458]
The test `TestBatchADVAddendum99Category` https://github.com/adelelopez/ach/blob/master/batchADV_test.go#L135 is not running into any errors, but the code looks like it is checking for one. There are numerous similar issues with addenda count and category checks with different batch types, which makes me think that the addenda count code has a bug in it. 

If these are working as expected, a comment to that effect should be given.

**Comment by adelelopez** [comment]
Here's another example of a test with this issue: https://github.com/adelelopez/ach/blob/master/batchCTX_test.go#L152

**Comment by bkmoovio** [comment]
Perfect, please create an issue and add these types of items to the issue or please create an issue for each and I can then take a look at them.

**Comment by bkmoovio** [comment]
As mentioned before I wrote about 1000 tests and I’m not a test writer.  If 20% of the tests are good, we are in great shape.  Anything above that is a bonus.

**Comment by bkmoovio** [comment]
A huge help to make sure the ach package is working as expected would be to put a break in every test to see if the test is functioning correctly.  The package might just be unusable and we might have to stay with legacy systems.

**Comment by adamdecaf** [comment]
@bkmoovio Go is supported by some debuggers: https://golang.org/doc/gdb

**Comment by bkmoovio** [comment]
Thats great.  I think we want to get a new set of eyes on all of the tests.  I refactored a lot of the original code and I wrote a lot of the tests and refactored many of the existing ones.  Clearly I’m very close to it.  Having you and Adele go through all of them would be a great help.
