### ISSUE TITLE
build: release prebuilt binaries 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#464]
We need to release pre-built binaries for Linux, macOS, and Windows on each release. This can be done with some tooling. The binaries should follow the same naming convention for each release going forward so tooling and our scripts can bump a version in the URL.

Example: https://github.com/pomerium/pomerium/commit/a2d647ee5bfb8091e1d13b3488860c520831faca 

Related: https://github.com/moov-io/docs/issues/27

**Comment by adamdecaf** [comment]
I've used these tools before, thoughts? 

- [github-release](https://github.com/aktau/github-release) for creating the release and uploading binaries
- [promu](https://github.com/prometheus/promu) for (cross-)building on one system. [Example Config](https://github.com/prometheus/promu/blob/master/doc/examples/prometheus/.promu.yml)

**Comment by adamdecaf** [comment]
Whatever we do will likely be copied to each project, so that's why I'm leaning towards using a couple tools rather than grow the makefile.

**Comment by wadearnold** [comment]
I have also used [gox](https://github.com/mitchellh/gox) and had a build script similar to the one used on Nats.io [cross_compile.sh](https://github.com/nats-io/gnatsd/blob/master/scripts/cross_compile.sh) and leverage the travis-ci `after_success:` and tagged as a release
