### ISSUE TITLE
File Header Immediate Origin field format

### ISSUE THREAD

**Issue by eduardev** [moov-io/ach#510]
https://github.com/moov-io/ach/blob/3609aa1ebe346a992170f545eee138d82d6df1a3/fileHeader.go#L37

In the field Godoc it says:

> The ach file format specifies a 10 character field
	// which begins with a blank space in the first position, followed by the four digit
	// Federal Reserve Routing Symbol, the four digit ABA Institution Identifier, and the Check
	// Digit (bTTTTAAAAC).  ImmediateOriginField() will append the blank space to the routing
	// number.

Where does it actually say this has to start with a blank space? I'm integrating with a bank and I was asked to change a bug I had in my files as the Immediate Origin (given by my ODFI) was missing the last digit and also had a "funny" blank space.

Indeed when looking at their spec, and also at [NACHA](https://www.nacha.org/system/files/resources/NACHA_ISO_20022_Guide_for_pain.008_%28direct_debit%29_Nov_2016%5B1%5D.docx) the only thing I see for this File Header field format is:

> (10-digit company number assigned by bank e.g., Tax ID):

As we're on a tight schedule I'm forking the project for quick fixing, and will submit a PR if you want, after discussing here.

**Comment by adamdecaf** [comment]
The rules and guidelines we based that off of mention a blank space. We'll check the more updated rules. 

<img width="425" alt="Screen Shot 2019-04-11 at 11 05 52 AM" src="https://user-images.githubusercontent.com/120951/55980702-e2443680-5c49-11e9-9378-bbe69925bf31.png">

Edit: From the doc you linked I see the following

> 10-digit company number assigned by bank (typically 9-digit tax ID preceded by "1")

**Comment by adamdecaf** [comment]
Our code should at least be 10-digit aware and not truncate the last digit. Yea, if you can submit a PR that'd be appreciated!

**Comment by themanchhina** [comment]
I'm running into a similar problem and wanted to check why this was reverted in https://github.com/moov-io/ach/pull/652?
From what I understand, `"1" + FID (9 digit Federal ID Number)` is also a valid immediate origin.

**Comment by adamdecaf** [comment]
The moov-io/ach library targets the latest Nacha specification for its default support. If you need a non-standard value in there you may have success with [`BypassOriginValidation`](https://pkg.go.dev/github.com/moov-io/ach#ValidateOpts.BypassOriginValidation)
