### ISSUE TITLE
File Creation - Padding

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#527]
File creation should default to NACHA rules by padding with ‘9’ the rows of the file to block account devisable by 10. Some legacy systems require the file to not be padded. Padding should be the default output of the file but when writing a file the client should be able to override if the file should be padded or not.
Rather than a configuration, this could be a post file creation process to remove the padding.

**Comment by adamdecaf** [comment]
We've got this padding by default. There have been no requests i can think of to deviate from the default, so I think we can close this. Thoughts @wadearnold ?

**Comment by wadearnold** [comment]
I agree.
