### ISSUE TITLE
File Creation - Flatten Batch’s

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#530]
File creation honours the order and number of Batch's that are created by the client. This processes are not optimized for the smallest file size and thus cost, that could be sent to the Federal Reserve for processing.  A Flatten or Optimize function should be created that merges any Batch Headers that have the same information and appends all entries into a single Batch

**Comment by bkmoovio** [comment]
We need Flatten for SEC Code IAT which has IATBatch and IATBatchHeader 

https://github.com/moov-io/ach/issues/611
