### ISSUE TITLE
File Creation - Balanced Offset

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ach#531]
A Balanced Offset is a Batch with Entry Detail that creates a balanced file. The offset is not a single net new entry. If there are debits, there is a credit offset. If there are credits, there is a debit offset. They are mutually exclusive. Offset files are used to offset transactions from a single account inside of the ODFI. The Offset is the last record which settles the funds into a single ODFI account. 

The process is to create a Batch Header with an Entry Detail providing the offsetting account information, amount, and summing all previous entries. 

The proposed solution is to add a function that would summarize the offset when a file was being created. 

Pseudocode 

```golang    
    // … assume all batches and corresponding entries have been added to the File 

    os_bh := NewBatchHeader()
    os_bh.StandardEntryClassCode = CCD
    os_bh.CompanyName = "ACME Corporation"
    os_bh.CompanyIdentification = "121042882"
    os_bh.CompanyEntryDescription = “OFFSET"
    os_bh.ODFIIdentification = “12104288”
   // All default properties will be overwritten when calculate

    os_entry := NewEntryDetail()
    os_entry.SetRDFI("121042882")
    os_entry.DFIAccountNumber = "123456789"
    os_entry.IndividualName = “OFFSET”
    // All default properties will be overwritten when calculated

    file.BalancedOffset(os_bh, os_entry)
    if err := file.Create(); err != nil {
        t.Fatalf("Unexpected error building file: %s\n", err)
    }
 ```

**Comment by bkmoovio** [comment]
With regard to: 'and summing all previous entries'

Should be able to use batch.GetControl().TotalDebitEntryDollarAmount  or  batch.GetControl().TotalCreditEntryDollarAmount, which ever is greater than zero to determine the offset amount.

If both are greater than zero we are unable to have one offset entry so return an error. 

If it is a new batch, create the BatchHeader data, create the Batch based on SEC Code, add the entry, add the Batch to the existing file (consider line count 10000) followed by file.Create() to create the new file.  

If it is a new entry in the batch, add the entry to the batch and call Batch.build(), followed by file.Create() to create a new file.  

Delete the old file?

**Comment by adamdecaf** [comment]
Sounds good. `file.Create()` doesn't make a new file, so there wouldn't be anything to cleanup.

**Comment by bkmoovio** [comment]
Thanks Adam, that's great!
