### ISSUE TITLE
Validate routing numbers by calling CheckRoutingNumber

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ach#554]
Validate routing numbers by calling CheckRoutingNumber.

Function CheckRoutingNumber was added to validate routing numbers via paygate and accounts. The ach go library should be updated to validate routing numbers by calling CheckRoutingNumber.

Appropriate test should be added to maintain code coverage.  

Do we want to consider calling FED to validate the routing number is a routing number per the Federal Reserve Bank listing?

**Comment by adamdecaf** [comment]
I would like to avoid having ACH's server depend on Fed. Paygate already checks Fed to ensure routing numbers exist there, so we don't need ACH to as well.

**Comment by bkmoovio** [comment]
Works for me.
