### ISSUE TITLE
fileCreationDate and fileCreationTime need more enforcement / error handling

### ISSUE THREAD

**Issue by eric-peterson-billgo** [moov-io/ach#556]
**What were you trying to do?**
These two fields are shown in this example :  https://github.com/moov-io/ach/blob/master/test/testdata/ppd-valid.json and also this format is allowed to be posted in with json.

**What did you expect to see?**
These fields should be of the format yyMMdd and HHmm in all examples, and ideally when posting json this should also be enforced, otherwise you get back a ACH file this is likely invalid.

**What did you see?**

**How can we reproduce the problem?**
Take the ppd json file above, and post it in, then grab the ACH file back.  Then try to post that ACH file back in as text and you will see the year is not right.

**Comment by adamdecaf** [comment]
Those fields support ISO8601 timestamps to allow languages to easier interop with our API. We return whatever format was given to us to keep the language's parser/reader happy.

There do seem to be missing validations and tests, which we can fix.

**Comment by bkmoovio** [comment]
The following is the original converter code, maybe it can be re-implemented or some variation of it.

// formatSimpleDate takes a time.Time and returns a string of YYMMDD
func (v *Converters) formatSimpleDate(t time.Time) string {
	return t.Format("060102")
}

// parseSimpleDate returns a time.Time when passed time as YYMMDD
func (v *Converters) parseSimpleDate(s string) time.Time {
	t, _ := time.Parse("060102", s)
	return t
}

// formatSimpleTime returns a string of HHMM when  passed a time.Time
func (v *Converters) formatSimpleTime(t time.Time) string {
	return t.Format("1504")
}

// parseSimpleTime returns a time.Time when passed a string of HHMM
func (v *Converters) parseSimpleTime(s string) time.Time {
	t, _ := time.Parse("1504", s)
	return t
}

**Comment by adamdecaf** [comment]
I have a different implementation of the fix. We need to handle both formats (timestamps and 4/6 number values).

**Comment by bkmoovio** [comment]
Thanks Adam!

**Comment by adamdecaf** [comment]
@eric-peterson-billgo Can you try out https://github.com/moov-io/ach/pull/558? It should handle the input a lot better and consistently format from ISO 8601 to YYMMDD/HHmm
