### ISSUE TITLE
cmd/server: add endpoint for segmenting a file along credit and debits

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#564]
Some Financial Institutions require ACH files are debit-only or credit-only. To help support this we can take an ACH file uploaded on the HTTP server (with needed library code) and return two files.

Think about an endpoint like this:

- `POST /files/:id/split?on=credit, debit` 

This endpoint would create two files and understand that `credit` and `debit` here mean credit-only and debit-only files. More known values could be added in the future.

The `FileHeader` and all Batches would be copied to both new files with their EntryDetails's split and re-tabulated. 

The response would contain both files: `[{ ... "fileHeader": ... }, { ... "fileHeader": ... }]`

**Comment by adamdecaf** [comment]
See https://github.com/moov-io/ach/pull/537 for some context

**Comment by adamdecaf** [comment]
Note: I changed back to `POST` because we're creating files in the ACH server, so it's a non-idempotent operation (new files have a random `ID`).

**Comment by bkmoovio** [comment]
Do we want this to be - `POST /files/:id/FileSegment`

**Comment by adamdecaf** [comment]
What about `POST /files/:id/segment`? Later on we can accept an optional JSON body with none being whatever defaults (split on debit and credits).

**Comment by bkmoovio** [comment]
Yeah that’s good!
