### ISSUE TITLE
The DFIAccountNumber field on EntryDetails should trim value after parsing ach file

### ISSUE THREAD

**Issue by rayjlinden** [moov-io/ach#631]
**What were you trying to do?**

View the field entry.DFIAccountNumber after parsing an ACH file.

**What did you expect to see?**

The string value to have white space trimmed.

**What did you see?**

The string value had white space padded to the right of the account number.

**How can we reproduce the problem?**

Parse and ACH file and print the value of the DFIAccountNumber field.

**Comment by adamdecaf** [comment]
Do you have the 2019 NACHA rules? This copy I'm reading from is a bit old (2013), but they state: 

<img width="446" alt="Screen Shot 2019-09-25 at 9 55 05 AM" src="https://user-images.githubusercontent.com/120951/65623030-c2949680-df7b-11e9-8bba-4fffda080a6c.png">

Looking at that description `"81967038518      "` makes sense to left justify and pad with spaces, but that's only on a receiver's account number.

In the event of a DFI's account number it looks like we should return `"81967038518"` (and handle placing `-`'s in where ` `'s are within the account number).

**Comment by adamdecaf** [comment]
If you're comparing against non-MICR account numbers I can see where having to trim the returned number is an extra step. 

All we specify on `DFIAccountNumberField()` is: 

> // DFIAccountNumberField gets the DFIAccountNumber with space padding

This doesn't really help as we don't perform ` ` (space) for `-` substitution in that method either.

**Comment by adamdecaf** [comment]
We could add a helper `ach.MICRNumber(string) string` which would convert `"1234 5678"` into ```"1234-5678        "``` (padded to 17 characters).

**Comment by adamdecaf** [comment]
cc @wadearnold I'm a bit confused what to do here

**Comment by adamdecaf** [comment]
Thoughts @wadearnold ?
