### ISSUE TITLE
v1.1.0 added validation around ImmediateOrigin that assumes it is always a routing number when there are cases when it may not be a routing number.

### ISSUE THREAD

**Issue by hitchr** [moov-io/ach#636]
**What were you trying to do?**
Create an ACH file with the CompanyId value as the ImmediateOrgin value as some banks request that.
**What did you expect to see?**
I expected to get a valid ACH file created
**What did you see?**
I received an error "Unexpected error building ACH file: ImmediateOrigin xxxxy routing number checksum mismatch: expected x but got y
**How can we reproduce the problem?**
Use a something other than a valid routing number for ImmediateOrigin.

**Also, here is where the code is for the validation:**
https://github.com/moov-io/ach/blob/master/fileHeader.go#L215

**Comment by hitchr** [comment]
The NACHA Rules and Guidelines state that it may not be a routing number in some cases.
"This field may also be mutually defined between ODFI and Originator.  For example, the ODFI may ask its Originator to put its Taxpayer Identification Number in this field..."

**Comment by bkmoovio** [comment]
Background history:

Wade A [11:08 PM]
I was thinking about adding a data model for Account Validation as a subtype to Depositories within PayGate. That would allow us to implement... Show more
wadearnold
Account validation is an important tool for businesses who originate ACH credits and debits. Using an incorrect routing and transit number and/or account number for the recipient of an ACH transaction can cost a business both...
moov-io/paygate | Jul 8th | Added by GitHub
:+1:1 reaction
general
–Jul 5th
Taylor [4:44 PM]
I created an issue about it, not sure yet if its only with depositories https://github.com/moov-io/paygate/issues/159... Show more
tgunnoe
Here's what exists in the database:
curl -X GET http://localhost:8082/depositories/eb7c9914cfc21eaf2ba2dbd517a1910a17a2b039 -H 'x-user-id: taylor'
...
moov-io/paygate | Jul 5th | Added by GitHub
adam
–Jun 24th
Brooke Kline [3:09 PM]
CheckRoutingNumber checks on length of 9, does that need to be updated to 10?
general
–Jun 21st
Brooke Kline [4:04 PM]
and if we wanted to implement FED we could make that part specific to wire and ach if CheckRoutingNumberdoesn't  error
general
–Jun 21st
adam [4:02 PM]
yea, I was hoping CheckRoutingNumber could be reused a lot
general
–Jun 21st

**adam [3:46 PM]
**Yea. We should use that to validate routing numbers all over. I’m pretty sure paygate or accounts use CheckRoutingNumber
general
–Jun 21st
Brooke Kline [3:43 PM]
Thats well after FileHeader, Batchheader and EntryDetail were created.  Should the properties that contain a routingnumber, use the CheckRoutingNumber validation function?
1 reply**
general
–Jun 21st
Brooke Kline [3:41 PM]
It looks like CheckRoutingNumber is not being used by anything, it was added Commits on Dec 17, 2018**
validators: add CheckRoutingNumber

**Comment by bkmoovio** [comment]
We added this validation specifically, so
func CheckRoutingNumber(routingNumber string) 

may need to be enhanced/fixed further.

**Comment by adamdecaf** [comment]
@hitchr v1.2.1 is being released now with this validation removed. We can add a method to validate this in v1.3.0 (as mentioned in slack).

For now `go get github.com/moov-io/ach@v1.2.1` should fix your immediate issue.

**Comment by hitchr** [comment]
Thanks.  That's awesome!
