### ISSUE TITLE
Addenda98: parse correction data 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#641]
**What were you trying to do?**

NOC files contain `CorrectedData string` which is a semi-structured format of correction data to update the ACH account with. We need to parse this field so paygate can update the respective object automatically for the user. 

**What did you expect to see?**

I think creating a struct called `CorrectedData` with various fields which is returned from a parser helper method would satisfy this feature in paygate and for other users. The fields would all be optional and only populated based on the correction code. 

```Go
func ParseCorrectionData(in string) (*CorrectedData, error)

type CorrectedData struct {
   AccountNumber string
   RoutingNumber string
   Name string
   TransactionCode int
   Identification string
}
```

For more details on each code and what fields it would populate: https://github.com/moov-io/paygate/blob/master/internal/filetransfer/correction.go#L85

**Comment by wadearnold** [comment]
Are their rules somewhere for parsing this data?

**Comment by adamdecaf** [comment]
NACHA's guidelines PDF has the rules, which I coped into [paygate's source as comments](https://github.com/moov-io/paygate/blob/master/internal/filetransfer/correction.go#L85) until we write the code to parse each.  Page OR 167 in the 2013 rules.
