### ISSUE TITLE
examples: create an AWS lambda of parsing ACH files

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#658]
It's come up a couple of times to offer a Lambda/Functions/etc example of parsing ACH files and writing them back somewhere (S3, SQS, etc). This seems useful for a lot of people who want to convert plain ACH files into JSON for processing somehow. 

If someone wants to offer an example of doing this we'd be happy to help get it merged.

**Comment by berryman17** [comment]
I should have some working examples for this today. Quick question, I've got NACHA-to-JSON working, but what method from your Go library should I use for JSON-to-NACHA?
