### ISSUE TITLE
Release v1.4.0

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#733]
It's time to make a release of ACH after lots of features have been added along with many bug fixes. Folks have been working from master or a release candidate tag, but we should offer a proper release. 

There's a draft changelog: https://github.com/moov-io/ach/blob/master/CHANGELOG.md#v140-unreleased

**Comment by adamdecaf** [comment]
@wadearnold I'm not going to include the custom TransactionCode / TraceNumbers in this release. Sound okay?

**Comment by wadearnold** [comment]
Yes this will be great. It's something that as we do posting files we will need like our discussion today
