### ISSUE TITLE
Set ImmediateOrigin to "0000000000" fails to generate NACHA

### ISSUE THREAD

**Issue by damonjanis** [moov-io/ach#742]
**What were you trying to do?**
Our customer is submitting the NACHA file to Chase. Chase requires ten zeros in the ImmediateOrigin field.

**What did you expect to see?**
Ten zeros in the Immediate Origin field.

**What did you see?**
Call fails with this error message, "ImmediateOrigin 0000000000 is a mandatory field and has a default value, did you use the constructor?"

**How can we reproduce the problem?**
Set the fileHeader.immediateOrigin to "0000000000"

**Comment by adamdecaf** [comment]
Can you try setting the File's `ValidateOpts{BypassOriginValidation: true}`? 

https://github.com/moov-io/ach/blob/v1.4.1/docs/custom-validation.md#origin

**Comment by adamdecaf** [comment]
@damonjanis Are you having this problem still?

**Comment by damonjanis** [comment]
I haven't been able to try it yet because my code is in C# using RestSharp to call the server and I don't have access to the ValidateOpts method.

**Comment by adamdecaf** [comment]
You should be able to call `POST /files/:id/validate` with a JSON body. On the HTTP server with v1.4.3 

https://moov-io.github.io/ach/api/#post-/files/{fileID}/validate

**Comment by adamdecaf** [comment]
Closing for now. Let us know if you have issues @damonjanis
