### ISSUE TITLE
File field of Reader is Not Exposed

### ISSUE THREAD

**Issue by jjafuller** [moov-io/ach#75]
In testing out the library, I notice that the file field of the Reader is not publicly accessible. I could be wrong, but I think this makes the library unusable as is? If that is intentional please disregard this observation. If not, I can submit a pull request to expose it. 

https://github.com/jjafuller/go-ach/commit/f5e5510ec62a168493e9a3fb8bbf6ef224b73dfb

**Comment by wadearnold** [comment]
please submit a pull request. I have yet to use it outside of my own projects.
