### ISSUE TITLE
achcli: flag that prepares a file for issue debugging

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#750]
**What were you trying to do?**
Sometimes a user will have a big file that is causing problems when parsing. It really helps to handoff the file with as close as possible bytes to what is having problems, but that file contains tons of PII. Is there a way we can mask that information in order to handoff for debugging. 

**What did you expect to see?**
A command people can run (on `achcli`) that removes PII so it can be handed off to the Moov team.

**Comment by vxio** [comment]
This would be a nice enhancement, I'll dig into this.
