### ISSUE TITLE
Library Does Not Support Files Without Line Breaks

### ISSUE THREAD

**Issue by jjafuller** [moov-io/ach#76]
I work with ACH files from a variety of sources, some have line feeds, some have carriage return line feed, and some do not have line breaks at all. The file I am experimenting with is the later. So, I tweaked the library to be able to support files without line breaks. If you would like this functionality I can submit a pull request.

https://github.com/jjafuller/go-ach/commit/56c13ede2f310c5fada0c3cb571f7468299e1103

**Comment by wadearnold** [comment]
Thank you! A pull request would be greatly appreciated. Just getting back from vacation.

**Comment by wadearnold** [comment]
If you can supply test cases I would really appreciate. Let me know if you can't supply a pull request and i will copy your gist over.
