### ISSUE TITLE
Running go get github.com/moov-io/ach causes error

### ISSUE THREAD

**Issue by ianberryman** [moov-io/ach#764]
**What were you trying to do?**
I was following the instructions in CONTRIBUTING.md to get the ach module to perform local development by calling: `go get github.com/moov-io/ach`

**What did you expect to see?**
I expected the module to download successfully

**What did you see?**
I received an error: 
```
package github.com/moov-io/ach        
        imports github.com/moov-io/base
        imports github.com/rickar/cal: no Go files in C:\Users\Me\go\src\github.com\rickar\cal
```

**How can we reproduce the problem?**
You can reproduce by running `go get github.com/moov-io/ach` in a new project

I managed to resolve this issue by running `go mod init <my-module-path>`  in my project and then running `go get github.com/moov-io/ach` again. I'm new to Go, so I'm not sure if this is an issue or just poor understanding on my part.

**Comment by adamdecaf** [comment]
I'll clarify that in our docs, thanks!
