### ISSUE TITLE
webui: "upload file" button

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#768]
It might be handy to have a button that reads a file which can then be parsed and formatted. Thoughts?

**Comment by adamdecaf** [comment]
cc @jmbrown412 thoughts? I just thought of this.

**Comment by jmbrown412** [comment]
> cc @jmbrown412 thoughts? I just thought of this.

I can work on this. I think it would be useful.

**Comment by adamdecaf** [comment]
Added in https://github.com/moov-io/ach/pull/765/commits/c5601e016190ead3c7ce21df9bbe4f925e1f1d66
