### ISSUE TITLE
spike: Sub Package for translating CSV/XSLS files into ACH files

### ISSUE THREAD

**Issue by GrahamMcBain** [moov-io/ach#775]
**What were you trying to do?**
Many people still manually generate ACH files from data held in CSVXSLS files. Creating a sub package that ingests these files and creates a Nacha compliant ACH file could save time for a large subset of people. 

What would the community like to see from a sub package that handles this use case?

**Comment by adamdecaf** [comment]
Somewhat related, but here's an XML spec for ACH files. It only partially covers the possible SEC codes, so I'm not sure how widely adopted this specification is. Looks to originate from IBM.

https://github.com/freight-trust/NACHA

**Comment by SharonAllsup** [comment]
I'd like to have error-checking mode where I can submit a file (or a single entry) and get a return code OK or not OK, without generating the actual output file.  Ideally it will let me identify a level of output detail for errors.

Just skimming that XML spec I can see a number of batch-related errors or issues that could come up.  A file might have the individual detail records pass OK but if they are supplying the batch-level data then there's the potential for mismatch there as well.  Which makes me wonder if there would be demand for a "generate the batch level records, too" type option?

**Comment by adamdecaf** [comment]
> I'd like to have error-checking mode where I can submit a file (or a single entry) and get a return code OK or not OK, without generating the actual output file. Ideally it will let me identify a level of output detail for errors.

Each major type (e.g. `BatchHeader`, `EntryDetail`, AddendaXX) supports a `Validate() error` method that follows the Nacha spec. Also, the returned error strings have information from what model they are from. Would that work to satisfy this? 

> Just skimming that XML spec ... 

That freight-trust/NACHA was posted in our slack and is an incomplete specification for ACH. I'm thinking we should ignore it for now. We could convert our JSON spec over to XML and have a complete specification.

**Comment by adamdecaf** [comment]
This is a bit too generic for us to implement. If there are specific examples we can highlight them.
