### ISSUE TITLE
Contrary to documentation, loading a file from JSON performs validation

### ISSUE THREAD

**Issue by benarena** [moov-io/ach#828]
I noticed this when trying to load an ACH file from JSON using `file.UnmarshalJSON`.

The documentation states that the resulting file should be validated, as it may be invalid.
https://github.com/moov-io/ach/blob/85a464f43f8b32f8e19cbe8767f764e3ba431959/file.go#L98-L103

However, before returning a successful file, validation is called resulting in an error:
https://github.com/moov-io/ach/blob/85a464f43f8b32f8e19cbe8767f764e3ba431959/file.go#L166-L168

I'd like to be able to validate my parsed file on my own after unmarshalling from JSON, and preferably without duplicating the behavior already present. My recommendation is to remove the validation, or at a minimum, update the documentation to more specifically address the behavior of the function.

**Comment by adamdecaf** [comment]
I can see where removing this check helps to keep errors from unmarshaling and validation isolated. It'd need to be in a new minor release. 

`return file, err` was meant to return the entire file even if Validation errors occurred, but it's non-trivial to detect which type of error was returned.
