### ISSUE TITLE
JSON Specification?

### ISSUE THREAD

**Issue by 5outh** [moov-io/ach#829]
ACH Version: `v1.5.2`

**What were you trying to do?**

Read from/write to ACH files using a Haskell data type with  `achcli`'s JSON format as an intermediate representation.

In order to do this effectively, I need to know exactly what the data type looks like. I ran the parser on two example files (one normal transaction, one return) and I can see that they differ - the return JSON contains fields that the normal transaction's JSON format does not (for example `addenda99`). How can I get more detail on how exactly this JSON is formatted without digging into the source code?

**What did you expect to see?**

A specification of the JSON format for `achcli` (data types, required, nullable, or optional)

**What did you see?**

I do not see a formal specification.

**How can we reproduce the problem?**

N/A

**Comment by vxio** [comment]
Hey @5outh, we're working on updating our [open api spec](./openapi.yaml) to specify the data types on each of our models. That way, you can look there to see a field's type and whether it's required/nullable/optional. Would that satisfy your use case?

**Comment by adamdecaf** [comment]
If there are specific examples where the OpenAPI spec is wrong please let us know.
