### ISSUE TITLE
Ability to designate starting point of Batch Sequence Number

### ISSUE THREAD

**Issue by Dartths** [moov-io/ach#841]
Version: v1.6.0

What were you trying to do?
Designate the batchnumber or starting point of the batch sequence via the create file api

What did you expect to see?
The batch numbers passed in with the batch headers to be used

What did you see?
Batch numbers start at 1 and iterate

This is a real world requirement I have where my downstream consumers use the batch number as a dedup mechanism  for the day so I need to be able to define the starting point for the batch

**Comment by vxio** [comment]
Thanks for submitting the issue! I'll submit a PR to address this within the next few days.

**Comment by eberttc** [comment]
I want to start batch number from 0 but the library override it with 1. Is there a reason for that rule?

**Comment by adamdecaf** [comment]
Is a BatchNumber of 0 even valid in Nacha?

**Comment by eberttc** [comment]
We are using a javascript lib called [nacha2](https://github.com/glenselle/nACH2/blob/b88355d5baaee9f47cb28fdfd15ba41b8018ecd0/lib/file/index.js#L24) for a while and by default set 0 .

**Comment by adamdecaf** [comment]
Ah cool. It's hard to tell if 0 is intentional or not, so we've set the minimum to 1. It works better across a variety of banks as well.
