### ISSUE TITLE
merge: lineCount can be improved

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#862]
ACH Version: `v1.6.2`

**What were you trying to do?**
When calling `MergeFiles` there's a function called `lineCount` that is used for when ACH files reach their Nacha designated limits. This is used to comply with Nacha guidelines that limit file lengths to 10k lines.

**What did you expect to see?**
The implementation of `lineCount` is a) inefficient and b) requires the file completes a call to `Create()` without error. 

**What did you see?**
`lineCount` should be as fast as possible. On large arrays of files the performance will not be optimal.

**Comment by adamdecaf** [comment]
@vxio I started this on a branch, but wanted your thoughts. It reimplements some logic in `Writer` to fully process the structs, but we can manage that as that logic won't change. 

https://github.com/adamdecaf/ach/blob/34b9274b4d8a48fd20c374032a0293da1e3ec93a/merge.go#L133

**Comment by vxio** [comment]
I'll take a look 👍🏻
