### ISSUE TITLE
file: FlattenBatches produces incorrectly ordered EntryDetail records

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#863]
ACH Version: `v1.6.2`

**What were you trying to do?**

**What did you expect to see?**

**What did you see?**

**How can we reproduce the problem?**

**Comment by vxio** [comment]
I'll look into this, this may not be an issue anymore given the recent refactor to FlattenBatches: https://github.com/moov-io/ach/commit/bdc08d224d6ff16e9664a8ed51fb1959e578410c

Do you have an example file I could test against?

**Comment by adamdecaf** [comment]
Fixed in https://github.com/moov-io/ach/pull/894
