### ISSUE TITLE
file: Should AddBatch insert at the correct position? 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#866]
ACH Version: `v1.6.2`

**What were you trying to do?**
When calling `AddBatch(..)` the Batch being added is currently appended to the end of the file. This works for some use-cases but also means fields like the BatchNumber and TraceNumbers need to be valid within the contents of that file. 

**What did you expect to see?**
`AddBatch(..)` should create valid files wherever possible. 

**What did you see?**
`AddBatch(..)` creates an invalid file.

**Comment by vxio** [comment]
I don't think we would want to add that responsibility to `AddBatch(..)`. The caller should call `Create()` after calling `AddBatch()` to transform the file into a valid state.
