### ISSUE TITLE
file: MergeFiles can produce invalid files 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach#867]
ACH Version: `v1.6.2`

**What were you trying to do?**
When calling `MergeFiles(...)` with multiple files you can get an `ach.File` out does not validate. This is from the ordering of input files that are appended to the output file, but done so in an incorrect ordering. 

**What did you expect to see?**
`MergeFiles(..)` should product valid files.

**What did you see?**
`MergeFiles(..)` produced an file which was not valid.

**Comment by vxio** [comment]
I'll look into this; do you have an example file I can run tests against?
