### ISSUE TITLE
file: a valid ACH file that is read in by the Reader fails validation on a call to Validate()

### ISSUE THREAD

**Issue by vxio** [moov-io/ach#904]
ACH Version: `v1.7.1`

**What were you trying to do?**
Read a valid ACH text file and call `File.Validate()`.
Link to file: https://github.com/moov-io/ach/blob/v1.7.1/cmd/readACH/201805101354.ach

**What did you expect to see?**
No error.

**What did you see?**
An error `"EntryHash calculated 35690050000 is out-of-balance with file control 5690050000"`

---
Details:
The entry hash that gets recalculated is 11 digits long -- but the file's entry hash gets cut down to 10 digits when `File.Create()` is called to satisfy Nacha requirements.

In `File.Validate()`, we need to account for integer lengths.

Link to public Slack thread for context: https://moov-io.slack.com/archives/CD9J8EJKX/p1618897030161000

**Comment by adamdecaf** [comment]
We explain this in the godoc for Read()

```
// A parsed file may not be valid and callers should ensure the file is validate with Validate()
// and tabulate the file with Create(). Invalid files may be rejected by other Financial Institutions or ACH tools.
func (r *Reader) Read() (File, error) {
```

**Comment by adamdecaf** [comment]
I agree we should fail Validate() when the 11-digit value overflows 10-digits.

**Comment by vxio** [comment]
Good point.

If the entry hash that's read in is 10 digits long, but the calculated entry hash is 11 digits long **but** matches the entry hash when the most significant bit gets lobbed off, should `Validate()` still throw an error? If so, we can close this issue since it's by design.

**Comment by vxio** [comment]
> We explain this in the godoc for Read()
> 
> ```
> // A parsed file may not be valid and callers should ensure the file is validate with Validate()
> // and tabulate the file with Create(). Invalid files may be rejected by other Financial Institutions or ACH tools.
> func (r *Reader) Read() (File, error) {
> ```

Closing this issue.

**Comment by adamdecaf** [comment]
@vxio can we ask Orlando about checking the overflow? Seems like we should do that still.
