### ISSUE TITLE
server: batch ID not set on POST to /files/create

### ISSUE THREAD

**Issue by vxio** [moov-io/ach#923]
ACH Version: `v1.8.0`

**What were you trying to do?**
Run the following commands against the server:
```bash
curl -X POST -H "content-type: application/json" -d "@ppd-valid.json" localhost:8080/files/create
// no error

curl localhost:8080/files/adam-01/batches/adam-01
// not found error
```
**What did you expect to see?**
Successfully fetching the batch by its ID.

**Cause**
Only `POST /files/{fileID}/batches` sets the batch ID from its header; but `POST /files/create` doesn't. So the batch ID remains empty.

**Comment by vxio** [comment]
@adamdecaf to confirm, this isn't by design right?

**Comment by adamdecaf** [comment]
Correct. This looks like a bug.
