### ISSUE TITLE
OpenAPI spec is missing and mis-typing some properties

### ISSUE THREAD

**Issue by benarena** [moov-io/ach#948]
This should be a trivial change that improves OpenAPI spec accuracy. The use case was generating a client library, but this applies equally to accurate specifications for your API.

ACH Version: `1.9.2`

**What were you trying to do?**
Generate Java client from OpenAPI spec

**What did you expect to see?**
A full spec with correct data types

**What did you see?**
Missing object: `ADVFileControl`

Missing properties in files:
- File
  - `fileADVControl`
- FIleHeader
  - `id`
  - `referenceCode`

Incorrectly typed fields:
`sequenceNumber`, `entryDetailSequenceNumber`, `Addenda10.foreignPaymentAmount` `IATEntryDetail.addendaRecords`, `ADVEntryDetail.julianDay` are typed as `number`, but should be typed as `integer` (they are not floating point) [OpenAPI data types](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#dataTypes)

**How can we reproduce the problem?**
Just look at the OpenAPI spec, or to create a client library (not really necessary):
```
curl --location --request POST 'https://generator3.swagger.io/api/generate' \
--header 'content-type: application/json' \
--data-raw '{
  "specURL" : "https://raw.githubusercontent.com/moov-io/ach/master/openapi.yaml",
  "lang" : "java",
  "type" : "CLIENT",
  "codegenVersion" : "V3"
}'
```

**Comment by adamdecaf** [comment]
Thanks for the bug report @benarena. You're right that those OpenAPI parameters are incorrectly typed.
